config/routes.rb
Finaddictz::Application.routes.draw do
  resources :advertisements

  resources :notifications

  resources :rivers

  resources :property_posts

  resources :messages
  
  resources :conversations

  resources :ratings

  resources :env_prefs

  resources :locations

  resources :angler_posts

  resources :guide_posts

  resources :fishing_methods

  resources :fish_species


  resources :user_sessions
  match "/logout" => "user_sessions#destroy"
  match "/login" => "user_sessions#new"
  match "/register" => "users#new"
  get '/forgot_password' => "users#forgot_password", :as => 'forgot_password'
  post '/forgot_password/send_new_password' => "users#send_new_password"

  match "/map" => "map#index"

  #for changing a trips status from open to pending
  match 'guide_posts/book_trip/:id/:user_id' => 'guide_posts#book_trip', :as => 'book_trip'

  match 'angler_posts/book_trip/:id/:user_id' => 'angler_posts#book_trip', :as => 'book_trip'

  #for confirming a user after they register 
  match 'users/confirm/:id/:sha' => 'users#confirm'

  #for changing a users role
  match 'users/:id/change_role/:role' => 'users#change_role', :as => 'change_role_user'

  #for viewing abusive posts
  get 'abusive_posts/:id' => 'guide_posts#abusive_posts', :as => 'abusive_posts'

  #enabling and disabling a user
  put "users/:id/toggle_enabled" => 'users#toggle_enabled', :as => 'toggle_enabled_user'

  put "guide_posts/:id/flag_as_abused" => 'guide_posts#flag_as_abused', :as => 'flag_guide_post_as_abused'
  put "property_posts/:id/flag_as_abused" => 'property_posts#flag_as_abused', :as => 'flag_property_post_as_abused'
  put "angler_posts/:id/flag_as_abused" => 'angler_posts#flag_as_abused', :as => 'flag_angler_post_as_abused'

  put "guide_posts/:id/flag_as_not_abused" => 'guide_posts#flag_as_not_abused', :as => 'flag_guide_post_as_not_abused'
  put "property_posts/:id/flag_as_not_abused" => 'property_posts#flag_as_not_abused', :as => 'flag_property_post_as_not_abused'
  put "angler_posts/:id/flag_as_not_abused" => 'angler_posts#flag_as_not_abused', :as => 'flag_angler_post_as_not_abused'

  delete "guide_posts/:id/remove_user_from_trip/:user_id" => 'guide_posts#remove_user_from_trip', :as => 'remove_user_from_trip'
  put "trips_to_users/:id/accept_user_on_trip/:user_id/:guide_post_id" => 'trips_to_users#accept_user_on_trip', :as => 'accept_user_on_trip'

  resources :users

  root :to => "user_sessions#new"


end

app/models/guide_post.rb
class GuidePost < ActiveRecord::Base
	#these are methods that are shared between AnglerPost and GuidePost
	include SharedPostMethods

	#validations
	class GuidePostValidator < ActiveModel::Validator
		#add custom validations to this method
	  def validate(record)
	  	interested_users = TripsToUser.find_all_by_post_id(record.id).count()
	    if interested_users > record.num_people && record.booking_status == BookingStatus.find_by_status("Booked")
	      record.errors[:num_people] << 'The number of users interested in your trip is greater than your initial estimate, you can fix this by removing users from the trip, or expanding the number of users for the trip.'
	    end
	    if interested_users == 0 && record.booking_status == BookingStatus.find_by_status("Booked")
	      record.errors[:num_people] << 'You must have people interested in your trip before you can mark it as booked.'
	    end
	  end
	end
	include ActiveModel::Validations


  [:title, :description, :date, :price_per].each do |v|
    validates v, :presence => true
  end
  validates :price_per, :numericality => { :greater_than_or_equal_to => 0 }
  validates :num_people, :numericality => { :greater_than_or_equal_to => 1 }

  validates_with GuidePostValidator

  #validates the date of trip is not in the past
  validate :not_past_date

	def not_past_date
	  if self.date.past?
	    errors.add(:date, 'of trip cannot be in the past')
	  end
	end

  #end validations

  #relations
	belongs_to :user
	belongs_to :river
	belongs_to :booking_status
	#end relations

	after_save :check_if_status_is_booked

	#has to go through booking validations first so we are good to just send out 
	#a notification to the user that requested the trip
	def check_if_status_is_booked
		if booking_status == BookingStatus.find_by_status("Booked")
			@trips = TripsToUser.find_all_by_post_id(self.id)
			@trips.each do |trip|
				Notification.create(
		      user_id: trip.user_who_agreed_id,
		      notification_type: NotificationType.find_by_name("trip_confirmed").id,
		      title: "Trip has been confirmed.",
		      message: "Your trip with #{self.user} is official, click the link below to view the trip details.",
		      related_id: self.id
		    )
			end
		end
	end

	def isFull?
		TripsToUser.find_all_by_post_id(self.id).count() >= num_people
	end

	def self.abusive_posts_count
		count = 0
		count += GuidePost.find_all_by_abusive_flag(true).count()
		count += AnglerPost.find_all_by_abusive_flag(true).count()
		count += PropertyPost.find_all_by_abusive_flag(true).count()
		count
	end
	
  #make guide posts more dynamically searchable sunspot
  searchable do
    text :title, :boost => 5 
    text :description
    integer :price_per
    time :date
    time :created_at
  end

  #called from the controller passed in params
  def self.fullSearch(params)
  	begin
  		
	  	search = GuidePost.search do
	  		#the full text search
	      fulltext params[:search]

	      #the pricing search params
	      params[:price_max] = 1000 if (params[:price_max] == nil)
	      params[:price_min] = 0 if (params[:price_min] == nil)
	      with(:price_per, params[:price_min].to_i..params[:price_max].to_i)

	      #expects 08/19/2012 for dates
	      if params[:start_date].present?
	      	t = string_to_time(params[:start_date])
		      with(:date).greater_than t
		    end 


	      if params[:end_date].present?
	      	
		      t = string_to_time(params[:end_date])
		      #with(:date).between(Time.mktime(2012, 8, 5)..Time.mktime(2012, 8, 6))
		      with(:date).less_than t
		    end 

		    
	      #with(:date).greater_than params[:start_date] if params[:start_date].present?
	      paginate :page => params[:page] || 1, :per_page => 10
	      order_by :created_at, :desc
	    end
	    search.results
	  #we'll just give a vanilla search if they really f something up and break the code above
	  rescue
	  	search = GuidePost.search do
	  		paginate :page => params[:page] || 1, :per_page => 10
	  		order_by :created_at, :desc
	  	end
	  	search.results
	  end
  end

end

app/controllers/guide_posts_controller.rb
class GuidePostsController < ApplicationController
  helper_method :valid_date_string
  # GET /guide_posts
  # GET /guide_posts.json
  def index
    if params == {"action"=>"index", "controller"=>"guide_posts"}
      params.merge!({:price_min => 0, :price_max => 1000})
    end
    @guide_posts  = GuidePost.fullSearch(params)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guide_posts }
    end
  end

  # GET /guide_posts/1
  # GET /guide_posts/1.json
  def show
    @guide_post = GuidePost.find(params[:id])
    @post_is_booked = true if @guide_post.booking_status == BookingStatus.find_by_status("Booked")
    @post_is_pending = true if @guide_post.booking_status == BookingStatus.find_by_status("Pending")
    if @post_is_pending
      @pending_users = TripsToUser.find_all_by_post_id(params[:id]).count()
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guide_post }
    end
  end

  # GET /guide_posts/new
  # GET /guide_posts/new.json
  def new
    @guide_post = GuidePost.new
    @rivers = River.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guide_post }
    end
  end

  # GET /guide_posts/1/edit
  def edit
    @guide_post = GuidePost.find(params[:id])
    @rivers = River.all
    interested_users = TripsToUser.find_all_by_post_id(params[:id])
    @interested_users = []
    @accepted_users = []
    interested_users.each do |trip|
      if trip.accepted
        @accepted_users.push({"user" => User.find_by_id(trip.user_who_agreed_id), "trip_id" => trip.id})
      else
        @interested_users.push({"user" => User.find_by_id(trip.user_who_agreed_id), "trip_id" => trip.id})
      end
    end
  end

  # POST /guide_posts
  # POST /guide_posts.json
  def create

    @guide_post = GuidePost.new(params[:guide_post])

    respond_to do |format|
      if @guide_post.save
        format.html { redirect_to @guide_post, notice: 'Guide post was successfully created.' }
        format.json { render json: @guide_post, status: :created, location: @guide_post }
      else
        format.html { render action: "new" }
        format.json { render json: @guide_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guide_posts/1
  # PUT /guide_posts/1.json
  def update
    @guide_post = GuidePost.find(params[:id])
    @rivers = River.all
    interested_users = TripsToUser.find_all_by_post_id(params[:id])
    @interested_user_count = interested_users.count()
    @users = []
    interested_users.each do |u|
      @users.push(User.find_by_id(u.user_who_agreed_id))
    end

    respond_to do |format|
      if @guide_post.update_attributes(params[:guide_post])
        format.html { redirect_to @guide_post, notice: 'Guide post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @guide_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guide_posts/1
  # DELETE /guide_posts/1.json
  def destroy
    @guide_post = GuidePost.find(params[:id])
    @guide_post.destroy

    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Your post has been deleted.' }
      format.json { head :ok }
    end
  end

  def flag_as_abused
    @guide_post = GuidePost.find(params[:id])
    @guide_post.abusive_flag = true;
    if @guide_post.save
      AbuseMailer.abuse_email.deliver
      redirect_to @guide_post, notice: 'Guide post was flagged as abusive.'
    else
      redirect_to @guide_post, notice: 'Cannot flag this post as abusive.'
    end
  end 

  def flag_as_not_abused
    @guide_post = GuidePost.find(params[:id])
    @guide_post.abusive_flag = false;
    if @guide_post.save
      redirect_to abusive_posts_path(1), notice: 'Guide post was flagged as unabusive.'
    else
      redirect_to abusive_posts_path(1), notice: 'Cannot flag this post as abusive.'
    end
  end  

  def book_trip
    @guide_post = GuidePost.find(params[:id])
    @guide_post.booking_status_id = BookingStatus.find_by_status("Pending").id;

    already_booked_this_trip = TripsToUser.find_by_post_id_and_user_who_agreed_id(params[:id], current_user.id)
    already_has_trip_on_this_day = current_user.has_conflicting_trip(@guide_post)

    unless already_booked_this_trip || already_has_trip_on_this_day
      #insert into trips users table here!
      TripsToUser.create(
        post_id: @guide_post.id,
        post_booking_status_id: @guide_post.booking_status_id,
        user_who_posted_id: @guide_post.user.id,
        user_who_agreed_id: current_user.id
      )

      Notification.create(
        user_id: @guide_post.user.id,
        notification_type: NotificationType.find_by_name("trip_booking").id,
        title: "#{current_user} has requested to book your trip: '#{@guide_post.title}'",
        message: "",
        related_id: @guide_post.id
      )

      if @guide_post.save
        redirect_to @guide_post, notice: 'The guide has been notified of your interest!'
      else
        redirect_to @guide_post, notice: 'Something went wrong..'
      end
    else 
      if already_has_trip_on_this_day
        redirect_to @guide_post, notice: 'You already have a trip booked for this day.'
      else 
        redirect_to @guide_post, notice: 'You have already sent a request for booking this trip.'
      end
    end
  end 

  def remove_user_from_trip
    @guide_post = GuidePost.find(params[:id])
    @trip = TripsToUser.find_by_post_id_and_user_who_agreed_id(params[:id], params[:user_id])
    @trip.destroy

    Notification.create(
      user_id: @trip.user_who_agreed_id,
      notification_type: NotificationType.find_by_name("trip_full").id,
      title: "Trip Full",
      message: "Unfortunately your trip with #{@guide_post.user} is full, you can contact #{@guide_post.user} for more details.",
      related_id: @guide_post.id
    )

    redirect_to edit_guide_post_url(params[:id]), notice: 'User has been informed that this slot has been taken.'
  end

  def abusive_posts
    @guide_posts = GuidePost.find_all_by_abusive_flag(true)
    @angler_posts = AnglerPost.find_all_by_abusive_flag(true)
    @property_posts = PropertyPost.find_all_by_abusive_flag(true)
  end

end

app/helpers/guide_posts_helper.rb
module GuidePostsHelper
end

app/views/guide_posts/abusive_posts.html.erb
<h4>Guide Posts:</h4>

<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>Date Posted</th>
			<th>Manage</th>
		</tr>
	</thead>
	<tbody>
		<% @guide_posts.each do |post| %>
			<tr>
				<td><%= post.title %></td>
				<td><%= post.description %></td>
				<td><%= post.created_at %></td>
				<td>
					<div class="btn-group">
            <button class="btn btnbtn-primary" align="center">Manage</button>
            <button class="btn btnbtn-primary" data-toggle="dropdown">
              <span class="caret"></span>
            </button>

            <ul class="dropdown-menu">
              <li><%= link_to 'View Post', guide_post_path(post) %></li>
              <li><%= link_to 'Edit Post', edit_guide_post_path(post) %></li>
              <li><%= link_to 'Flag as unabusive', flag_guide_post_as_not_abused_path(post), confirm: 'Are you sure?', method: :put  %></li>
              <li><%= link_to 'Delete Post', post, confirm: 'Are you sure?', method: :delete %></li>
            </ul>
          </div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<div class="clear"></div>
<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>Date Posted</th>
			<th>Manage</th>
		</tr>
	</thead>
	<tbody>
		<% @angler_posts.each do |post| %>
			<tr>
				<td><%= post.title %></td>
				<td><%= post.description %></td>
				<td><%= post.created_at %></td>
				<td>
					<div class="btn-group">
            <button class="btn btnbtn-primary" align="center">Manage</button>
            <button class="btn btnbtn-primary" data-toggle="dropdown">
              <span class="caret"></span>
            </button>

            <ul class="dropdown-menu">
              <li><%= link_to 'View Post', angler_post_path(post) %></li>
              <li><%= link_to 'Edit Post', edit_angler_post_path(post) %></li>
              <li><%= link_to 'Flag as unabusive', flag_angler_post_as_not_abused_path(post), confirm: 'Are you sure?', method: :put  %></li>
              <li><%= link_to 'Delete Post', post, confirm: 'Are you sure?', method: :delete %></li>
            </ul>
          </div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<div class="clear"></div>
<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>Date Posted</th>
			<th>Manage</th>
		</tr>
	</thead>
	<tbody>
		<% @property_posts.each do |post| %>
			<tr>
				<td><%= post.title %></td>
				<td><%= post.description %></td>
				<td><%= post.created_at %></td>
				<td>
					<div class="btn-group">
            <button class="btn btnbtn-primary" align="center">Manage</button>
            <button class="btn btnbtn-primary" data-toggle="dropdown">
              <span class="caret"></span>
            </button>

            <ul class="dropdown-menu">
              <li><%= link_to 'View Post', property_post_path(post) %></li>
              <li><%= link_to 'Edit Post', edit_property_post_path(post) %></li>
              <li><%= link_to 'Flag as unabusive', flag_property_post_as_not_abused_path(post), confirm: 'Are you sure?', method: :put  %></li>
              <li><%= link_to 'Delete Post', post, confirm: 'Are you sure?', method: :delete %></li>
            </ul>
          </div>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/guide_posts/edit.html.erb
<legend>Editing Guide Post</legend>
<% if @interested_users.count > 0 %>
	<div class="alert alert-success">
		You have <b><%= pluralize(@interested_users.count, 'user') %></b> interested in this trip.<br/><br/>
    Your options are:
    <ul>
      <li>Accept an individual person for the trip.</li>
      <li>Accept everyone on the trip by changing the booking status below to "Booked".</li>
      <li>Let a person know the trip is full by clicking "Deny Request".</li>
    </ul>
	</div>
	<h5>Interested Users:</h5>
	<div class="span4">
		<% @interested_users.each do |user| %>
			<p>
				<%= user["user"] %>
			</p>
			<%= link_to 'View Profile', user_path(user["user"]), :class => 'btn btn-small' %> 
      <%= link_to 'Accept Request', "/trips_to_users/#{user["trip_id"]}/accept_user_on_trip/#{user["user"].id}/#{@guide_post.id}", :class => 'btn btn-small btn-success', :method => 'PUT' %>
			<%= link_to 'Deny Request', "/guide_posts/#{@guide_post.id}/remove_user_from_trip/#{user["user"].id}", :class => 'btn btn-small btn-danger', :method => 'DELETE' %>
			
			<hr/>
		<% end %>
	</div>
<% end %>
<div class="clear"></div>
<% if @accepted_users.count > 0 %>
  <h5>Accepted Users:</h5>
  <div class="span4">
    <% @accepted_users.each do |user| %>
      <p>
        <%= user["user"] %>
      </p>
      <%= link_to 'View Profile', user_path(user["user"]), :class => 'btn btn-small' %> 
      <%= link_to 'Deny Request', "/guide_posts/#{@guide_post.id}/remove_user_from_trip/#{user["user"].id}", :class => 'btn btn-small btn-danger', :method => 'DELETE' %>
      <hr/>
    <% end %>
  </div>
<% end %>
<div class="clear"></div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script> 

<%= form_for(@guide_post, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @guide_post.errors.any? %>
    <div class="alert alert-error">
      <% @guide_post.errors.full_messages.each do |msg| %>
      <ul>  
        <li><%= msg %></li>
      </ul>
      <% end %>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="control-group">
    <%= f.label :title, :class => "control-label"%>
    <div class="controls">
      <%= f.text_field :title, :class => "text_field"  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :description, :class => "text_field" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :num_people, :class => "control-label" %>
    <div class="controls">
      <%= f.number_field :num_people, :class => "text_field" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price_per, :class => "control-label" %>
    <div class="controls">
      <%= f.number_field :price_per, :class => "text_field" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => "control-label" %>
    <div class="controls">
      <%= f.date_select :date, :class => "text_field" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :time, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :time, :class => "text_field" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "Trip Status:", :class => "control-label" %>
    <div class="controls">
      <%= f.select :booking_status_id, BookingStatus.all.reverse!.collect {|s| [ s, s.id ] } %>
    </div>
  </div>

  <%= f.hidden_field :latitude, :id => 'latitude_hidden_field' %>  
  <%= f.hidden_field :longitude, :id => 'longitude_hidden_field' %>
  <div class="control-group">
    <div class="controls">
      <%= f.select :river_id, @rivers.collect {|r| [ r, r.id ] }, :include_blank => "Select River" %>
    </div>
  </div>
  
  <div class="control-group">
    <div class="controls">
      <div id="map_canvas" style="width: 550px; height: 450px"></div> 
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Update Post', :class => 'btn btn-primary' %>
  </div>
    <% end %>




<script type="text/javascript"> 
//<![CDATA[
  $(document).ready(function () {
     // global "map" variable
      var map = null;
      var marker = null;

      var infowindow = new google.maps.InfoWindow(
        { 
          size: new google.maps.Size(150,50)
        });

      // A function to create the marker and set up the event window function 
      function createMarker(latlng, name, html) {
          var contentString = html;
          var marker = new google.maps.Marker({
              position: latlng,
              map: map,
              zIndex: Math.round(latlng.lat()*-100000)<<5
              });

          google.maps.event.addListener(marker, 'click', function() {
              infowindow.setContent(contentString); 
              infowindow.open(map,marker);
              });
          google.maps.event.trigger(marker, 'click');    
          return marker;
      }

       

      function initialize() {
        // create the map
        var myOptions = {
          zoom: 10,
          center: new google.maps.LatLng(<%=@guide_post.latitude%>, <%=@guide_post.longitude%>),
          mapTypeControl: true,
          mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
          navigationControl: true,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        map = new google.maps.Map(document.getElementById("map_canvas"),
                                      myOptions);

        var latlng = new google.maps.LatLng(<%=@guide_post.latitude%>, <%=@guide_post.longitude%>); 

        marker = createMarker(latlng, "name");

       
        google.maps.event.addListener(map, 'click', function() {
          infowindow.close();
        });


      }
      initialize();


      
    });
//]]>
</script> 

app/views/guide_posts/show.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script> 
<!-- <div class="top-ad"><%=getAdForPage('Trip Detail').html_safe%></div> -->
<div class="row">
  <div class="span8">
    <p>Posted By:</p>
    <div class="profile_info_wrapper">
      <div class="profile_picture">
        <%= image_tag  @guide_post.user.photo.url(:small), :class => "img-polaroid" %>
      </div>
      <%= link_to @guide_post.user, @guide_post.user %>
      <p><%= @guide_post.user.about %></p>
    </div>  
    <% if @post_is_pending %>
      <div>This trip currently has <%= @pending_users %> people interested</div> 
    <% end %>
    <table class="table table-bordered table-striped">
      <colgroup>
        <col class="span1">
        <col class="span7">
      </colgroup>
      <thead>
        <tr>
          <th>Title</th>
          <th>
            <% if @guide_post.user == current_user %>
              <div id="edit_profile"><%= link_to 'Edit Post', edit_guide_post_path(@guide_post)%> <i class="icon-pencil"></i></div>
            <% end %>
            <span class="post_title"><%= @guide_post.title %></span>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Description</td>
          <td><%= @guide_post.description %></td>
        </tr>
        <tr>
          <td>Number of People</td>
          <td><%= @guide_post.num_people %></td>
        </tr>
        <tr>
          <td>Cost per Person</td>
          <td>$<%= @guide_post.price_per %></td>
        </tr>
        <tr>
          <td>Trip Date</td>
          <td><%= @guide_post.date %></td>
        </tr>
        <tr>
          <td>Status</td>
          <td>This trip is currently <%= @guide_post.booking_status %></td>
        </tr> 
        <tr>
          <td>River</td>
          <td><%= @guide_post.river %></td>
        </tr>   
        <tr>
          <td colspan=2>         
            <div class="btn-group">
                <button class="btn btn-primary" align="center">More</button>
                <button class="btn btn-primary" data-toggle="dropdown">
                  <span class="caret"></span>
                </button>

                <ul class="dropdown-menu">
                  <li><a href="#messageModal" role="button" data-toggle="modal">Message Guide</a></li>
                  <li><%= link_to 'Identify as Abusive', flag_guide_post_as_abused_path(@guide_post), :method => :put %></li>
                  <% unless @post_is_booked %>
                    <li class="divider"></li>
                    <li><%= link_to 'Book this trip!', "/guide_posts/book_trip/#{@guide_post.id}/#{current_user.id}" %></li>
                  <% end %>
                </ul>
              </div>
            </td>    
          </tr>       

      </tbody>
    </table>
    
    <div id="map_canvas" style="width: 550px; height: 450px"></div> 
  </div>
</div>

<div id="messageModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none; ">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Send an inquiry</h3>
  </div>
  <div class="modal-body">
    
    <% @conversation = Conversation.new %>
    <%= form_for(@conversation, :html => {:class => 'form-horizontal'}) do |f| %>
      
      <p>Message to: <%= @guide_post.user %></p>
      <%= f.hidden_field :user_id2, :value => @guide_post.user.id %>
      
      <%= f.hidden_field :user_id1, :value => current_user.id %>

      <div class="control-group">
        <%= f.label :title, :class => "control-label"%>
        <div class="controls">
          <%= f.text_field :title, :class => "text_field"  %>
        </div>
      </div>

      <input id="conversation_messages_attributes_0_user_id" name="conversation[messages_attributes][0][user_id]" type="hidden" value="<%= current_user.id %>">
      <div class="control-group">
        <%= f.label :text, :class => "control-label"  %>
        <div class="controls">
          <textarea class="text_field" id="conversation_messages_attributes_0_text" name="conversation[messages_attributes][0][text]" rows="10"></textarea>
        </div>
      </div>
      

      <div class="form-actions">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <%= f.submit 'Send', :class => 'btn btn-primary' %>
      </div>
    <% end %>
</div>


<script type="text/javascript"> 
//<![CDATA[
  $(document).ready(function () {
     // global "map" variable
      var map = null;
      var marker = null;

      var infowindow = new google.maps.InfoWindow(
        { 
          size: new google.maps.Size(150,50)
        });

      // A function to create the marker and set up the event window function 
      function createMarker(latlng, name, html) {
          var contentString = html;
          var marker = new google.maps.Marker({
              position: latlng,
              map: map,
              zIndex: Math.round(latlng.lat()*-100000)<<5
              });

          google.maps.event.addListener(marker, 'click', function() {
              infowindow.setContent(contentString); 
              infowindow.open(map,marker);
              });
          google.maps.event.trigger(marker, 'click');    
          return marker;
      }

       

      function initialize() {
        // create the map
        var myOptions = {
          zoom: 10,
          center: new google.maps.LatLng(<%=@guide_post.latitude%>, <%=@guide_post.longitude%>),
          mapTypeControl: true,
          mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
          navigationControl: true,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        map = new google.maps.Map(document.getElementById("map_canvas"),
                                      myOptions);

        var latlng = new google.maps.LatLng(<%=@guide_post.latitude%>, <%=@guide_post.longitude%>); 

        marker = createMarker(latlng, "name");

       
        google.maps.event.addListener(map, 'click', function() {
          infowindow.close();
        });


      }
      initialize();


      
    });
//]]>
</script> 