config/routes.rb
Finaddictz::Application.routes.draw do
  resources :advertisements

  resources :notifications

  resources :rivers

  resources :property_posts

  resources :messages
  
  resources :conversations

  resources :ratings

  resources :env_prefs

  resources :locations

  resources :angler_posts

  resources :guide_posts

  resources :fishing_methods

  resources :fish_species


  resources :user_sessions
  match "/logout" => "user_sessions#destroy"
  match "/login" => "user_sessions#new"
  match "/register" => "users#new"
  get '/forgot_password' => "users#forgot_password", :as => 'forgot_password'
  post '/forgot_password/send_new_password' => "users#send_new_password"

  match "/map" => "map#index"

  #for changing a trips status from open to pending
  match 'guide_posts/book_trip/:id/:user_id' => 'guide_posts#book_trip', :as => 'book_trip'

  match 'angler_posts/book_trip/:id/:user_id' => 'angler_posts#book_trip', :as => 'book_trip'

  #for confirming a user after they register 
  match 'users/confirm/:id/:sha' => 'users#confirm'

  #for changing a users role
  match 'users/:id/change_role/:role' => 'users#change_role', :as => 'change_role_user'

  #for viewing abusive posts
  get 'abusive_posts/:id' => 'guide_posts#abusive_posts', :as => 'abusive_posts'

  #enabling and disabling a user
  put "users/:id/toggle_enabled" => 'users#toggle_enabled', :as => 'toggle_enabled_user'

  put "guide_posts/:id/flag_as_abused" => 'guide_posts#flag_as_abused', :as => 'flag_guide_post_as_abused'
  put "property_posts/:id/flag_as_abused" => 'property_posts#flag_as_abused', :as => 'flag_property_post_as_abused'
  put "angler_posts/:id/flag_as_abused" => 'angler_posts#flag_as_abused', :as => 'flag_angler_post_as_abused'

  put "guide_posts/:id/flag_as_not_abused" => 'guide_posts#flag_as_not_abused', :as => 'flag_guide_post_as_not_abused'
  put "property_posts/:id/flag_as_not_abused" => 'property_posts#flag_as_not_abused', :as => 'flag_property_post_as_not_abused'
  put "angler_posts/:id/flag_as_not_abused" => 'angler_posts#flag_as_not_abused', :as => 'flag_angler_post_as_not_abused'

  delete "guide_posts/:id/remove_user_from_trip/:user_id" => 'guide_posts#remove_user_from_trip', :as => 'remove_user_from_trip'
  put "trips_to_users/:id/accept_user_on_trip/:user_id/:guide_post_id" => 'trips_to_users#accept_user_on_trip', :as => 'accept_user_on_trip'

  resources :users

  root :to => "user_sessions#new"


end

app/models/env_pref.rb
class EnvPref < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/env_prefs_controller.rb
class EnvPrefsController < ApplicationController
  # GET /env_prefs
  # GET /env_prefs.json
  def index
    @env_prefs = EnvPref.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @env_prefs }
    end
  end

  # GET /env_prefs/1
  # GET /env_prefs/1.json
  def show
    @env_pref = EnvPref.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @env_pref }
    end
  end

  # GET /env_prefs/new
  # GET /env_prefs/new.json
  def new
    @env_pref = EnvPref.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @env_pref }
    end
  end

  # GET /env_prefs/1/edit
  def edit
    @env_pref = EnvPref.find(params[:id])
  end

  # POST /env_prefs
  # POST /env_prefs.json
  def create
    @env_pref = EnvPref.new(params[:env_pref])

    respond_to do |format|
      if @env_pref.save
        format.html { redirect_to @env_pref, notice: 'Env pref was successfully created.' }
        format.json { render json: @env_pref, status: :created, location: @env_pref }
      else
        format.html { render action: "new" }
        format.json { render json: @env_pref.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /env_prefs/1
  # PUT /env_prefs/1.json
  def update
    @env_pref = EnvPref.find(params[:id])

    respond_to do |format|
      if @env_pref.update_attributes(params[:env_pref])
        format.html { redirect_to @env_pref, notice: 'Env pref was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @env_pref.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /env_prefs/1
  # DELETE /env_prefs/1.json
  def destroy
    @env_pref = EnvPref.find(params[:id])
    @env_pref.destroy

    respond_to do |format|
      format.html { redirect_to env_prefs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/env_prefs_helper.rb
module EnvPrefsHelper
end

app/views/env_prefs/_form.html.erb
<%= form_for(@env_pref) do |f| %>
  <% if @env_pref.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@env_pref.errors.count, "error") %> prohibited this env_pref from being saved:</h2>

      <ul>
      <% @env_pref.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/env_prefs/edit.html.erb
<h1>Editing env_pref</h1>

<%= render 'form' %>

<%= link_to 'Show', @env_pref %> |
<%= link_to 'Back', env_prefs_path %>

app/views/env_prefs/index.html.erb
<h1>Environmental Preferences</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @env_prefs.each do |env_pref| %>
  <tr>
    <td><%= env_pref.name %></td>
    <td><%= link_to 'Show', env_pref %></td>
    <td><%= link_to 'Edit', edit_env_pref_path(env_pref) %></td>
    <td><%= link_to 'Destroy', env_pref, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Env pref', new_env_pref_path %>

app/views/env_prefs/new.html.erb
<h1>New Environmental Preference</h1>

<%= render 'form' %>

<%= link_to 'Back', env_prefs_path %>

app/views/env_prefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @env_pref.name %>
</p>


<%= link_to 'Edit', edit_env_pref_path(@env_pref) %> |
<%= link_to 'Back', env_prefs_path %>