config/routes.rb
Finaddictz::Application.routes.draw do
  resources :advertisements

  resources :notifications

  resources :rivers

  resources :property_posts

  resources :messages
  
  resources :conversations

  resources :ratings

  resources :env_prefs

  resources :locations

  resources :angler_posts

  resources :guide_posts

  resources :fishing_methods

  resources :fish_species


  resources :user_sessions
  match "/logout" => "user_sessions#destroy"
  match "/login" => "user_sessions#new"
  match "/register" => "users#new"
  get '/forgot_password' => "users#forgot_password", :as => 'forgot_password'
  post '/forgot_password/send_new_password' => "users#send_new_password"

  match "/map" => "map#index"

  #for changing a trips status from open to pending
  match 'guide_posts/book_trip/:id/:user_id' => 'guide_posts#book_trip', :as => 'book_trip'

  match 'angler_posts/book_trip/:id/:user_id' => 'angler_posts#book_trip', :as => 'book_trip'

  #for confirming a user after they register 
  match 'users/confirm/:id/:sha' => 'users#confirm'

  #for changing a users role
  match 'users/:id/change_role/:role' => 'users#change_role', :as => 'change_role_user'

  #for viewing abusive posts
  get 'abusive_posts/:id' => 'guide_posts#abusive_posts', :as => 'abusive_posts'

  #enabling and disabling a user
  put "users/:id/toggle_enabled" => 'users#toggle_enabled', :as => 'toggle_enabled_user'

  put "guide_posts/:id/flag_as_abused" => 'guide_posts#flag_as_abused', :as => 'flag_guide_post_as_abused'
  put "property_posts/:id/flag_as_abused" => 'property_posts#flag_as_abused', :as => 'flag_property_post_as_abused'
  put "angler_posts/:id/flag_as_abused" => 'angler_posts#flag_as_abused', :as => 'flag_angler_post_as_abused'

  put "guide_posts/:id/flag_as_not_abused" => 'guide_posts#flag_as_not_abused', :as => 'flag_guide_post_as_not_abused'
  put "property_posts/:id/flag_as_not_abused" => 'property_posts#flag_as_not_abused', :as => 'flag_property_post_as_not_abused'
  put "angler_posts/:id/flag_as_not_abused" => 'angler_posts#flag_as_not_abused', :as => 'flag_angler_post_as_not_abused'

  delete "guide_posts/:id/remove_user_from_trip/:user_id" => 'guide_posts#remove_user_from_trip', :as => 'remove_user_from_trip'
  put "trips_to_users/:id/accept_user_on_trip/:user_id/:guide_post_id" => 'trips_to_users#accept_user_on_trip', :as => 'accept_user_on_trip'

  resources :users

  root :to => "user_sessions#new"


end

app/models/fish_specy.rb
class FishSpecy < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/fish_species_controller.rb
class FishSpeciesController < ApplicationController
  # GET /fish_species
  # GET /fish_species.json
  def index
    @fish_species = FishSpecy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fish_species }
    end
  end

  # GET /fish_species/1
  # GET /fish_species/1.json
  def show
    @fish_specy = FishSpecy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fish_specy }
    end
  end

  # GET /fish_species/new
  # GET /fish_species/new.json
  def new
    @fish_specy = FishSpecy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fish_specy }
    end
  end

  # GET /fish_species/1/edit
  def edit
    @fish_specy = FishSpecy.find(params[:id])
  end

  # POST /fish_species
  # POST /fish_species.json
  def create
    @fish_specy = FishSpecy.new(params[:fish_specy])

    respond_to do |format|
      if @fish_specy.save
        format.html { redirect_to @fish_specy, notice: 'Fish specy was successfully created.' }
        format.json { render json: @fish_specy, status: :created, location: @fish_specy }
      else
        format.html { render action: "new" }
        format.json { render json: @fish_specy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fish_species/1
  # PUT /fish_species/1.json
  def update
    @fish_specy = FishSpecy.find(params[:id])

    respond_to do |format|
      if @fish_specy.update_attributes(params[:fish_specy])
        format.html { redirect_to @fish_specy, notice: 'Fish specy was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fish_specy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish_species/1
  # DELETE /fish_species/1.json
  def destroy
    @fish_specy = FishSpecy.find(params[:id])
    @fish_specy.destroy

    respond_to do |format|
      format.html { redirect_to fish_species_url }
      format.json { head :ok }
    end
  end
end

app/helpers/fish_species_helper.rb
module FishSpeciesHelper
end

app/views/fish_species/_form.html.erb
<%= form_for(@fish_specy) do |f| %>
  <% if @fish_specy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish_specy.errors.count, "error") %> prohibited this fish_specy from being saved:</h2>

      <ul>
      <% @fish_specy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fish_species/edit.html.erb
<h1>Editing fish_specy</h1>

<%= render 'form' %>

<%= link_to 'Show', @fish_specy %> |
<%= link_to 'Back', fish_species_path %>

app/views/fish_species/index.html.erb
<h1>Fish Species</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fish_species.each do |fish_specy| %>
  <tr>
    <td><%= fish_specy.name %></td>
    <td><%= link_to 'Show', fish_specy %></td>
    <td><%= link_to 'Edit', edit_fish_specy_path(fish_specy) %></td>
    <td><%= link_to 'Destroy', fish_specy, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fish specy', new_fish_specy_path %>

app/views/fish_species/new.html.erb
<h1>New Fish Specy</h1>

<%= render 'form' %>

<%= link_to 'Back', fish_species_path %>

app/views/fish_species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fish_specy.name %>
</p>


<%= link_to 'Edit', edit_fish_specy_path(@fish_specy) %> |
<%= link_to 'Back', fish_species_path %>